
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 715572
	#The name of the modpack
	modpackName = "All The Mods 9"
	#The version of the modpack
	modpackVersion = "1.0.6"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

