
[general]
	"Enable 'q' Button" = false
	#Set to false to disable the popup message telling you that you can config quark in the q menu
	"Enable Onboarding" = false

[automation]
	"Feeding Trough" = false
	"Pistons Move Tile Entities" = false

[management]
	"Inventory Sorting" = false

[tweaks]
	"Automatic Recipe Unlock" = false
	"Simple Harvest" = false

	[tweaks.utility_recipes]
		"Easy Sticks" = false

[world]
	"Big Stone Clusters" = false

[client]
	"Back Button Keybind" = false

[building]
	"Celebratory Lamps" = true
	"Compressed Blocks" = true
	"Duskbound Blocks" = true
	"Framed Glass" = true
	"Glass Item Frame" = true
	"Gold Bars" = true
	Grate = true
	Hedges = true
	"Hollow Logs" = true
	"Industrial Palette" = true
	"Japanese Palette" = true
	"Leaf Carpet" = true
	Midori = true
	"More Brick Types" = true
	"More Mud Blocks" = true
	"More Potted Plants" = true
	"Nether Brick Fence Gate" = true
	"Rainbow Lamps" = true
	"Raw Metal Bricks" = true
	Rope = true
	"Shear Vines" = true
	Shingles = true
	"Soul Sandstone" = true
	Stools = true
	"Sturdy Stone" = false
	Thatch = true
	"Variant Bookshelves" = true
	"Variant Chests" = false
	"Variant Furnaces" = true
	"Variant Ladders" = true
	"Vertical Planks" = true
	"Vertical Slabs" = true
	"Wooden Posts" = true
	"More Stone Variants" = true



	[tweaks.double_door_opening]
		"Enable Doors" = true
		"Enable Fence Gates" = true
		#This feature disables itself if any of the following mods are loaded:
		# - utilitix
		#This is done to prevent content overlap.
		#You can turn this on to force the feature to be loaded even if the above mods are also loaded.
		"Ignore Anti Overlap" = true