#Display a 'tip' message at spawn?
sayThanksMessage = false
#How fast can you rotate when mounted to a camera and holding W-A-S-D?
#Range: 0.0 ~ 1.7976931348623157E308
cameraSpeed = 2.0
#Should reinforced blocks' textures be slightly darker than their vanilla counterparts? This setting can be overridden by servers.
reinforced_block_tint = true
#Set the color that reinforced blocks' textures have when reinforced_block_tint is enabled. This cannot be overridden by servers, and will be applied the same to all blocks. Grayscale values look best.
#Format: 0xRRGGBB
#Range: 0 ~ 16777215
reinforced_block_tint_color = 10066329

