	[tweaks.lantern_tweaks]
		#Allow wall lanterns placement
		enabled = true
		#Gives high priority to wall lantern placement. Enable to override other wall lanterns placements, disable if it causes issues with other mods that use lower priority block click events
		high_priority = true
		#Mod ids of mods that have lantern block that extend the base lantern class but don't look like one
		mod_blacklist = ["extlights", "betterendforge", "tconstruct", "enigmaticlegacy"]
		#Allows ceiling lanterns to fall if their support is broken.Additionally if they fall from high enough they will break creating a fire where they land
		#Allowed Values: ON, OFF, NO_FIRE
		falling_lanterns = "OFF"
	
	[tweaks.sus_recipes]
		#Adds recipes to craft suspicious gravel and suspicious sand
		enabled = false

#General settings
[general]
	#Disable startup messages and sanity check that the mod performs to inform of possible detected crashes that might occur due to issues
	sanity_checks_messages = false