
[World]

	[World.Features]

		[World.Features."Oil Sand"]
			#Whether this feature should naturally spawn in the world.
			Enable = true

		[World.Features.Apatite]
			#Whether this feature should naturally spawn in the world.
			Enable = false

		[World.Features.Silver]
			#Whether this feature should naturally spawn in the world.
			Enable = false

		[World.Features.Lead]
			#Whether this feature should naturally spawn in the world.
			Enable = false

		[World.Features.Nickel]
			#Whether this feature should naturally spawn in the world.
			Enable = false

		[World.Features.Cinnabar]
			#Whether this feature should naturally spawn in the world.
			Enable = false

		[World.Features.Sulfur]
			#Whether this feature should naturally spawn in the world.
			Enable = false

		[World.Features.Tin]
			#Whether this feature should naturally spawn in the world.
			Enable = false

		[World.Features.Niter]
			#Whether this feature should naturally spawn in the world.
			Enable = true

